# Generated by Django 5.1.1 on 2025-06-16 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Execution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre de la ejecución', max_length=100)),
                ('runtime', models.DurationField(help_text='tiempo de ejecución')),
                ('path_events_log', models.CharField(max_length=2048)),
                ('metrics', models.CharField(max_length=100)),
                ('miner', models.CharField(max_length=100)),
                ('constraints', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Optimizer',
            fields=[
                ('execution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pm_app.execution')),
                ('name', models.CharField(max_length=100)),
                ('hip_params', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Petri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('places', models.TextField()),
                ('transitions', models.TextField()),
                ('arcs', models.TextField()),
                ('is_pareto', models.BooleanField(default=False)),
                ('id_on_exec', models.PositiveIntegerField()),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pm_app.execution')),
            ],
        ),
        migrations.CreateModel(
            name='DSolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variables', models.JSONField()),
                ('objectives', models.JSONField()),
                ('constraints', models.JSONField()),
                ('is_pareto', models.BooleanField(default=False)),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pm_app.execution')),
                ('petri', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='solution', to='pm_app.petri')),
            ],
        ),
    ]
