# Generated by Django 5.1.1 on 2025-08-25 18:29

from django.db import migrations
import pandas as pd
import numpy as np

def recalculate_is_pareto(apps, schema_editor):
    DSolution = apps.get_model("pm_app", "DSolution")
    Petri = apps.get_model("pm_app", "Petri")
    Execution = apps.get_model("pm_app", "Execution")

    def pareto_front_df(df: pd.DataFrame):
        data = df.values
        is_dominated = np.zeros(len(data), dtype=bool)

        for i, sol1 in enumerate(data):
            for j, sol2 in enumerate(data):
                if i != j:
                    if np.all(sol2 <= sol1) and np.any(sol2 < sol1):
                        is_dominated[i] = True
                        break
        return df.loc[~is_dominated].drop_duplicates()

    for execution in Execution.objects.all():
        solutions = DSolution.objects.filter(execution=execution)

        if not solutions.exists():
            continue

        # Crear DataFrame directamente desde listas
        df = pd.DataFrame(
            [s.objectives for s in solutions],
            index=[s.id for s in solutions]
        )

        # Calcular frente de Pareto
        pareto_df = pareto_front_df(df)

        # IDs de soluciones que están en el frente
        pareto_ids = set(pareto_df.index)

        # Resetear todos a False
        solutions.update(is_pareto=False)

        # Marcar solo los del frente de Pareto
        DSolution.objects.filter(id__in=pareto_ids).update(is_pareto=True)
        Petri.objects.filter(id__in=pareto_ids).update(is_pareto=True)


def reverse_noop(apps, schema_editor):
    # No revertimos nada
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('pm_app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(recalculate_is_pareto, reverse_noop)
    ]
