# Generated by Django 5.1.1 on 2025-11-24 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm_app', '0002_recalculate_pareto'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrontSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.PositiveIntegerField(help_text='Índice de fichero FUN.x')),
                ('evaluations', models.PositiveIntegerField(blank=True, null=True)),
                ('objectives', models.JSONField(help_text='Vectores de objetivos del frente en ese paso')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fronts', to='pm_app.execution')),
            ],
            options={
                'unique_together': {('execution', 'step')},
            },
        ),
    ]
